### PR TITLE
Add fukamachi's frequently-updated products.

### PR DESCRIPTION
**Pull request by fukamachi**
Added 10 products:

- [Clack](https://github.com/fukamachi/clack)
- [Lack](https://github.com/fukamachi/lack)
- [Woo](https://github.com/fukamachi/woo)
- [Utopian](https://github.com/fukamachi/utopian)
- [Mito](https://github.com/fukamachi/mito)
- [SxQL](https://github.com/fukamachi/sxql)
- [Dexador](https://github.com/fukamachi/dexador)
- [QURI](https://github.com/fukamachi/quri)
- [Rove](https://github.com/fukamachi/rove)
- [Qlot](https://github.com/fukamachi/qlot)

### CODE REVIEW

**Comment by svetlyak40wt** [comment]
Great idea to add these projects.

Did you setup a webhook for them?

**Comment by svetlyak40wt** [comment]
Interesting. Now building of the project with quickdist fails on woo:

```
Component "uiop" not found
   [Condition of type MISSING-COMPONENT]

Restarts:
 0: [ABORT] Give up on "uiop"
 1: [ABORT] Give up on "cffi-grovel"
 2: [RETRY-LOAD] Retry loading #P"/app/build/sources/fukamachi-woo/woo.asd"
 3: [SKIP-LOAD] Skip loading #P"/app/build/sources/fukamachi-woo/woo.asd"
 4: [LOAD-OTHER] Load other file instead of #P"/app/build/sources/fukamachi-woo/woo.asd"
 5: [RETRY] Retry #<DEFINE-OP> on #<UNDEFINED-SYSTEM "woo">.
 --more--

Backtrace:
  0: (#<STANDARD-METHOD OPERATE (SYMBOL T)> LOAD-OP "uiop" :VERBOSE NIL)
  1: (CCL::%%BEFORE-AND-AFTER-COMBINED-METHOD-DCODE ((NIL) #<STANDARD-METHOD OPERATE (SYMBOL T)> LOAD-OP "uiop" :VERBOSE NIL))
  2: (CCL::%CALL-NEXT-METHOD ((NIL) #<STANDARD-METHOD OPERATE (SYMBOL T)> LOAD-OP "uiop" :VERBOSE NIL))
  3: ((:INTERNAL (OPERATE :AROUND (T T))))
  4: (#<STANDARD-METHOD OPERATE :AROUND (T T)> LOAD-OP "uiop" :VERBOSE NIL)
  5: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<STANDARD-METHOD OPERATE :AROUND (T T)> (#<STANDARD-METHOD OPERATE :BEFORE #>) (#<STANDARD-METHOD OPERATE :AFTER #>) #<STANDARD-METHOD OPERATE (SYMBOL T)>) 175..
  6: (NIL #<Unknown Arguments>)
  7: (LOAD-SYSTEM "uiop" :VERBOSE NIL)
  8: (QUICKLISP-CLIENT::CALL-WITH-MACROEXPAND-PROGRESS #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL QUICKLISP-CLIENT::APPLY-LOAD-STRATEGY) #x3020060F939F>)
  9: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "uiop" :PROMPT NIL)
 10: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "cffi-grovel" :PROMPT NIL)
 11: (#<STANDARD-METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)> #<QL-IMPL:CCL #x30200074C1FD> #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL QUICKLISP-CLIENT::QL ..))
 12: (#<STANDARD-METHOD QUICKLISP-CLIENT:QUICKLOAD (T)> (:CFFI-GROVEL) :PROMPT NIL :SILENT NIL :VERBOSE NIL)
 13: (CCL::%CALL-NEXT-METHOD ((NIL) #<STANDARD-METHOD QUICKLISP-CLIENT:QUICKLOAD (T)> :CFFI-GROVEL))
 14: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL (QUICKLISP-CLIENT:QUICKLOAD :AROUND (T))) #x3020060CFB7F>)
 15: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<STANDARD-METHOD QUICKLISP-CLIENT:QUICKLOAD :AROUND (T)> #<STANDARD-METHOD QUICKLISP-CLIENT:QUICKLOAD (T)>) 17557234342232)
 16: (NIL #<Unknown Arguments>)
 17: (CCL::CALL-CHECK-REGS QUICKLISP-CLIENT:QUICKLOAD :CFFI-GROVEL)
 18: ((:INTERNAL CCL::WITH-COMPILATION-UNIT-BODY CCL::LOAD-FROM-STREAM))
```

Seems, it don't like https://github.com/fukamachi/woo/blob/master/woo.asd#L37 line.

**Comment by svetlyak40wt** [comment]
In manual mode all systems were included into the distribution, but I need to handle this situation with uiop, before it will be possible to update it automatically.

**Comment by fukamachi** [comment]
It because the older version of Clozure CL (1.9) bundles old ASDF which doesn't have UIOP.
On such those implementations, it requires to load UIOP from Quicklisp, since UIOP is also distributed via Quicklisp.

**Comment by fukamachi** [comment]
It may be unnecessary for implementations bundling ASDF 3.1 or later.
I'm considering to add `#+asdf3.1` after some investigations.

**Comment by svetlyak40wt** [comment]
Interesting. Because I have recent ASDF. And when I try to search UIOP system right from the repl, Im able to find it:
```
CL-USER> (asdf:asdf-version)
"3.3.2.2"
CL-USER> (asdf:find-system :uiop)
#<SYSTEM "uiop">
```

Looks like a bug somewhere in the quickdist's version I use.

**Comment by svetlyak40wt** [comment]
Yeah, I found the problem. It is in this line:

https://github.com/ultralisp/quickdist/blob/master/quickdist.lisp#L191

Will fix it asap.

**Comment by svetlyak40wt** [comment]
Interesting, even after I've fixed a bug https://github.com/ultralisp/quickdist/commit/b7deefc22a88920a5303a5f84bfcaf94483fa6e5 within quickdist, it generates 
```
fukamachi-woo woo cffi-grovel alexandria cffi cffi-toolchain
```

And what is more strange, it generates few lines for woo (and some other projects too):

```
fukamachi-woo woo cffi alexandria babel trivial-features uiop
fukamachi-woo woo cffi alexandria babel trivial-features uiop
fukamachi-woo woo cffi alexandria babel trivial-features uiop
fukamachi-woo woo cffi-grovel alexandria cffi cffi-toolchain
```

I need to go deeper!

**Pull request merged**
